job1:
  only:
    - master
  script:
    - source /home/fpga/.bashrc
    - mkdir build && cd build
    - cmake ..
    - cmake --build . --target all -- -j4
    - ctest
    - cmake --build . --target quartus-analysis-all
